import * as urlRepository from "./url.repository.js";
import type { CreateShortenUrlInput } from "./url.types.js";

function badRequest(message: string): Error & { statusCode: number } {
  return Object.assign(new Error(message), { statusCode: 400 });
}

function notFound(message: string): Error & { statusCode: number } {
  return Object.assign(new Error(message), { statusCode: 404 });
}

function assertHttpUrl(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    throw badRequest("Original Url Required");
  }
  let parsed: URL;
  try {
    parsed = new URL(trimmed);
  } catch {
    throw badRequest("Invalid URL");
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw badRequest("Invalid URL");
  }
  return trimmed;
}

export async function getShortenUrl(shortCode: string) {
  if (!shortCode || shortCode.trim().length === 0) {
    throw badRequest("Short Code Required!");
  }

  const url = await urlRepository.findShortenUrlByShortCode(shortCode);

  if (!url || !url.originalUrl) {
    throw notFound("Short URL not found");
  }

  return {
    originalUrl: url.originalUrl,
  };
}

export async function createShortenUrl(data: CreateShortenUrlInput) {
  const originalUrl = assertHttpUrl(data?.originalUrl ?? "");

  // short_code is generated by the Postgres BEFORE INSERT trigger
  // (generate_short_url, WHEN short_code IS NULL), so only the
  // originalUrl is sent. Prisma returns the trigger-filled row.
  const url = await urlRepository.createShortenUrl({ originalUrl });

  if (!url.shortCode) {
    throw Object.assign(new Error("Short code generation failed"), {
      statusCode: 500,
    });
  }

  return {
    shortenUrl: url.shortCode,
  };
}
